### ISSUE TITLE
UE4 crash during play in Editor

### ISSUE THREAD

**Issue by SebGrinke** [BlenderSleuth/FlyingNavSystemSupport#3] opened 2021-08-08 20:40 UTC
<img width="1078" alt="NewBug" src="https://user-images.githubusercontent.com/4033291/128645075-79409597-8590-4c22-ada9-81d938e5a748.PNG">

**Comment by BlenderSleuth** [comment] 2021-08-08 23:29
Hey, thanks very much for these reports! The marketplace update fixing the issue is taking longer than expected to come through, but it shouldn't be too long before you can update

**Comment by BlenderSleuth** [comment] 2021-08-16 08:35
Fixed with 1.0.7

**Closed as completed by BlenderSleuth** 2021-08-16 08:35 UTC
Labels: bug
